version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn compile package
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Veracode
      - curl -L -o VeracodeJavaAPI.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/20.12.7.3/vosp-api-wrappers-java-20.12.7.3.jar
      - java -jar VeracodeJavaAPI.jar -vid $VERACODE_ID -vkey $VERACODE_KEY -action uploadandscan -appname "AWS-VeraDemo" -createprofile true -filepath target/verademo.war -version $(date +%Y-%m-%d-%H:%M) -scantimeout 60
artifacts:
  files:
    - target/verademo.war
    - appspec.yml
  discard-paths: yes