#Steps:
# Veracode Software Composition Analysis
# Veracode Static Analysis Asynchronous Upload and Scan
# Veracode Static Analysis PipelineScan
# Import flaws to Azure Boards
version: 2.1
jobs:
  build:
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: maven:3.6.3-openjdk-8
    working_directory: ~/target
    steps:
      - checkout
      - run:
          name: Run Maven
          command: 'mvn compile package'
      # keep the files around for the scan job
      - persist_to_workspace:
          root: ./
          paths:
            - target
            - ./
  # job to upload to Veracode for scanning
  veracode_sast:
    # use a java-based image to run the Veracode API wrapper
    docker:
      - image: signiant/docker-jenkins-centos7-java8:latest
    #working_directory: ~/target
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: ./    
      # grab the Veracode agent
      - run:
          name: "Get the Veracode agent"
          command: |
            wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.2.7.4/vosp-api-wrappers-java-21.2.7.4.jar
          #chmod 755 veracode-wrapper.jar
      - run:
          name: "Upload to Veracode"
          command: java -jar veracode-wrapper.jar 
              -vid $TEAM_ANALYSISCENTER_ID
              -vkey $TEAM_ANALYSISCENTER_KEY
              -action uploadandscan 
              -appname "Verademo_circleci"
              -createprofile true 
              -version CircleCI-$CIRCLE_BUILD_NUM 
              -filepath ./target/verademo.war
 # job to upload to Veracode for Agent Based SCA scanning
  Veracode_sca:
    docker:
      # specify the version you desire here
      - image: signiant/docker-jenkins-centos7-java8:latest
      #- image: maven:3.6.3-openjdk-8
    #working_directory: ~/repo
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: ./
      # download and run Veracode SCA
      - run:
          name: "Veracode Software Composition Analysis"
          command: |
            export SRCCLR_SCM_TOKEN=$github_api
            export SRCCLR_SCM_TYPE=GITHUB
            git config --global user.email "$emailgit"
            git config --global user.name "$nomegit"
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git checkout master
            export EXTRA_ARGS='--update-advisor --pull-request'
            #sudo yum check-update
            curl -fsSL https://get.docker.com/ | sh
            sudo systemctl start docker
            sudo systemctl status docker
            curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --image maven:3.6.3-openjdk-8 || true
            curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan $EXTRA_ARGS

 # job to perform a Veracode Pipeline Scan
  Veracode_pipelinescan:
    docker: 
      - image: signiant/docker-jenkins-centos7-java8:latest  
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: ./
      # Downlowad the scanner
      - run:
         name: "Download Veracode Pipeline Scan"
         command: |
           curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - run:
         name: "Unzip Veracode Pipeline Scan"
         command: |
           unzip pipeline-scan-LATEST.zip
      - run:
         name: "Run Veracode Pipeline Scan  and create a baseline"
         command: |
           java -jar pipeline-scan.jar -vid $TEAM_ANALYSISCENTER_ID -vkey $TEAM_ANALYSISCENTER_KEY -f ./target/verademo.war --json_output_file="baseline.json"
# serial jobs - need to run 'build' before 'scan'
workflows:
  version: 2.1
  build_and_scan:
    jobs:
      - build
      - Veracode_sca:
          requires:
            - build
      - veracode_sast:
          requires:
            - build
      - Veracode_pipelinescan:
          requires:
            - build
      

